name: 'Run script'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  UpdatePlugins:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Set up node 18.x'
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: 'Install dependencies'
        run: npm ci
        working-directory: scripts
      - name: 'Run script'
        timeout-minutes: 10
        run: node -r esbuild-register ./index.ts
        id: node
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        working-directory: scripts/
      - name: 'Commit'
        run: |
          git config --local user.email "github-actions[bot]"
          git config --local user.name "github-actions[bot]@users.noreply.github.com"
          git add --all
          git commit -m "Update JSONs"
          git push